from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol

from _mydbg import (
    Breakpoint,
    CommandResult,
    ExpressionResult,
    Snapshot,
    _text,
)

__doc__ = _text("PythonPackageTypingDoc")


class Process(Protocol):
    def send(self, data: bytes, timeout: float = 10.0) -> None: ...
    def sendline(self, data: bytes = b"", timeout: float = 10.0) -> None: ...
    def recv(self, size: int = 4096, timeout: float = 10.0) -> bytes: ...
    def recvuntil(self, delimiter: bytes, timeout: float = 10.0) -> bytes: ...


class Debugger(Protocol):
    def load(self, executable: str, timeout: float = 10.0) -> Snapshot: ...
    def launch(
        self,
        argv: Sequence[str],
        stop_at: str = "main",
        environment: Mapping[str, str] = {},
        cwd: str = "",
        timeout: float = 10.0,
    ) -> Process: ...
    def attach(self, process_id: int, timeout: float = 10.0) -> Process: ...
    def restart(self, timeout: float = 10.0) -> Process: ...
    def detach(self, timeout: float = 10.0) -> None: ...
    def terminate(self, timeout: float = 10.0) -> None: ...
    def continue_execution(self, timeout: float = 10.0) -> None: ...
    def continue_and_wait(self, timeout: float = 10.0) -> Snapshot: ...
    def interrupt(self, timeout: float = 10.0) -> None: ...
    def interrupt_and_wait(self, timeout: float = 10.0) -> Snapshot: ...
    def step_instruction(
        self, step_over: bool = False, timeout: float = 10.0
    ) -> Snapshot: ...
    def run_to(self, address: int, timeout: float = 10.0) -> Snapshot: ...
    def disassemble(self, address: int, timeout: float = 10.0) -> Snapshot: ...
    def wait_for_stop(self, timeout: float = 10.0) -> Snapshot: ...
    def wait_for_exit(self, timeout: float = 10.0) -> Snapshot: ...
    def snapshot(self) -> Snapshot: ...
    def evaluate(self, expression: str, timeout: float = 10.0) -> ExpressionResult: ...
    def read_register(self, name: str, timeout: float = 10.0) -> int: ...
    def write_register(self, name: str, value: int, timeout: float = 10.0) -> None: ...
    def read_memory(self, address: int, size: int, timeout: float = 10.0) -> bytes: ...
    def write_memory(self, address: int, data: bytes, timeout: float = 10.0) -> None: ...
    def select_thread(self, thread_id: int, timeout: float = 10.0) -> None: ...
    def select_frame(
        self, thread_id: int, frame_index: int, timeout: float = 10.0
    ) -> None: ...
    def set_breakpoint(self, specification: str, timeout: float = 10.0) -> int: ...
    def remove_breakpoint(self, breakpoint_id: int, timeout: float = 10.0) -> None: ...
    def enable_breakpoint(
        self, breakpoint_id: int, enabled: bool = True, timeout: float = 10.0
    ) -> None: ...
    def list_breakpoints(self) -> list[Breakpoint]: ...
    def execute(self, command: str, timeout: float = 10.0) -> CommandResult: ...
